/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCadreRouteImport } from './routes/_authenticated/cadre'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedCadreIndexRouteImport } from './routes/_authenticated/cadre.index'
import { Route as AuthenticatedDashboardUsersRouteImport } from './routes/_authenticated/dashboard.users'
import { Route as AuthenticatedDashboardReportsRouteImport } from './routes/_authenticated/dashboard.reports'
import { Route as AuthenticatedDashboardHelpRouteImport } from './routes/_authenticated/dashboard.help'
import { Route as AuthenticatedDashboardEvidenceRouteImport } from './routes/_authenticated/dashboard.evidence'
import { Route as AuthenticatedDashboardAttendanceRouteImport } from './routes/_authenticated/dashboard.attendance'
import { Route as AuthenticatedDashboardApprovalsRouteImport } from './routes/_authenticated/dashboard.approvals'
import { Route as AuthenticatedDashboardActivitiesRouteImport } from './routes/_authenticated/dashboard.activities'
import { Route as AuthenticatedCadreSubmitRouteImport } from './routes/_authenticated/cadre.submit'
import { Route as AuthenticatedCadreProfileRouteImport } from './routes/_authenticated/cadre.profile'
import { Route as AuthenticatedCadreNotificationsRouteImport } from './routes/_authenticated/cadre.notifications'
import { Route as AuthenticatedCadreHistoryRouteImport } from './routes/_authenticated/cadre.history'
import { Route as AuthenticatedCadreHelpRouteImport } from './routes/_authenticated/cadre.help'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCadreRoute = AuthenticatedCadreRouteImport.update({
  id: '/cadre',
  path: '/cadre',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedCadreIndexRoute = AuthenticatedCadreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCadreRoute,
} as any)
const AuthenticatedDashboardUsersRoute =
  AuthenticatedDashboardUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardReportsRoute =
  AuthenticatedDashboardReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardHelpRoute =
  AuthenticatedDashboardHelpRouteImport.update({
    id: '/help',
    path: '/help',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardEvidenceRoute =
  AuthenticatedDashboardEvidenceRouteImport.update({
    id: '/evidence',
    path: '/evidence',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAttendanceRoute =
  AuthenticatedDashboardAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardApprovalsRoute =
  AuthenticatedDashboardApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardActivitiesRoute =
  AuthenticatedDashboardActivitiesRouteImport.update({
    id: '/activities',
    path: '/activities',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedCadreSubmitRoute =
  AuthenticatedCadreSubmitRouteImport.update({
    id: '/submit',
    path: '/submit',
    getParentRoute: () => AuthenticatedCadreRoute,
  } as any)
const AuthenticatedCadreProfileRoute =
  AuthenticatedCadreProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedCadreRoute,
  } as any)
const AuthenticatedCadreNotificationsRoute =
  AuthenticatedCadreNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedCadreRoute,
  } as any)
const AuthenticatedCadreHistoryRoute =
  AuthenticatedCadreHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedCadreRoute,
  } as any)
const AuthenticatedCadreHelpRoute = AuthenticatedCadreHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedCadreRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cadre': typeof AuthenticatedCadreRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/cadre/help': typeof AuthenticatedCadreHelpRoute
  '/cadre/history': typeof AuthenticatedCadreHistoryRoute
  '/cadre/notifications': typeof AuthenticatedCadreNotificationsRoute
  '/cadre/profile': typeof AuthenticatedCadreProfileRoute
  '/cadre/submit': typeof AuthenticatedCadreSubmitRoute
  '/dashboard/activities': typeof AuthenticatedDashboardActivitiesRoute
  '/dashboard/approvals': typeof AuthenticatedDashboardApprovalsRoute
  '/dashboard/attendance': typeof AuthenticatedDashboardAttendanceRoute
  '/dashboard/evidence': typeof AuthenticatedDashboardEvidenceRoute
  '/dashboard/help': typeof AuthenticatedDashboardHelpRoute
  '/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/dashboard/users': typeof AuthenticatedDashboardUsersRoute
  '/cadre/': typeof AuthenticatedCadreIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/cadre/help': typeof AuthenticatedCadreHelpRoute
  '/cadre/history': typeof AuthenticatedCadreHistoryRoute
  '/cadre/notifications': typeof AuthenticatedCadreNotificationsRoute
  '/cadre/profile': typeof AuthenticatedCadreProfileRoute
  '/cadre/submit': typeof AuthenticatedCadreSubmitRoute
  '/dashboard/activities': typeof AuthenticatedDashboardActivitiesRoute
  '/dashboard/approvals': typeof AuthenticatedDashboardApprovalsRoute
  '/dashboard/attendance': typeof AuthenticatedDashboardAttendanceRoute
  '/dashboard/evidence': typeof AuthenticatedDashboardEvidenceRoute
  '/dashboard/help': typeof AuthenticatedDashboardHelpRoute
  '/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/dashboard/users': typeof AuthenticatedDashboardUsersRoute
  '/cadre': typeof AuthenticatedCadreIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/cadre': typeof AuthenticatedCadreRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/cadre/help': typeof AuthenticatedCadreHelpRoute
  '/_authenticated/cadre/history': typeof AuthenticatedCadreHistoryRoute
  '/_authenticated/cadre/notifications': typeof AuthenticatedCadreNotificationsRoute
  '/_authenticated/cadre/profile': typeof AuthenticatedCadreProfileRoute
  '/_authenticated/cadre/submit': typeof AuthenticatedCadreSubmitRoute
  '/_authenticated/dashboard/activities': typeof AuthenticatedDashboardActivitiesRoute
  '/_authenticated/dashboard/approvals': typeof AuthenticatedDashboardApprovalsRoute
  '/_authenticated/dashboard/attendance': typeof AuthenticatedDashboardAttendanceRoute
  '/_authenticated/dashboard/evidence': typeof AuthenticatedDashboardEvidenceRoute
  '/_authenticated/dashboard/help': typeof AuthenticatedDashboardHelpRoute
  '/_authenticated/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/_authenticated/dashboard/users': typeof AuthenticatedDashboardUsersRoute
  '/_authenticated/cadre/': typeof AuthenticatedCadreIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cadre'
    | '/dashboard'
    | '/home'
    | '/cadre/help'
    | '/cadre/history'
    | '/cadre/notifications'
    | '/cadre/profile'
    | '/cadre/submit'
    | '/dashboard/activities'
    | '/dashboard/approvals'
    | '/dashboard/attendance'
    | '/dashboard/evidence'
    | '/dashboard/help'
    | '/dashboard/reports'
    | '/dashboard/users'
    | '/cadre/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/home'
    | '/cadre/help'
    | '/cadre/history'
    | '/cadre/notifications'
    | '/cadre/profile'
    | '/cadre/submit'
    | '/dashboard/activities'
    | '/dashboard/approvals'
    | '/dashboard/attendance'
    | '/dashboard/evidence'
    | '/dashboard/help'
    | '/dashboard/reports'
    | '/dashboard/users'
    | '/cadre'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/cadre'
    | '/_authenticated/dashboard'
    | '/_authenticated/home'
    | '/_authenticated/cadre/help'
    | '/_authenticated/cadre/history'
    | '/_authenticated/cadre/notifications'
    | '/_authenticated/cadre/profile'
    | '/_authenticated/cadre/submit'
    | '/_authenticated/dashboard/activities'
    | '/_authenticated/dashboard/approvals'
    | '/_authenticated/dashboard/attendance'
    | '/_authenticated/dashboard/evidence'
    | '/_authenticated/dashboard/help'
    | '/_authenticated/dashboard/reports'
    | '/_authenticated/dashboard/users'
    | '/_authenticated/cadre/'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadre': {
      id: '/_authenticated/cadre'
      path: '/cadre'
      fullPath: '/cadre'
      preLoaderRoute: typeof AuthenticatedCadreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/cadre/': {
      id: '/_authenticated/cadre/'
      path: '/'
      fullPath: '/cadre/'
      preLoaderRoute: typeof AuthenticatedCadreIndexRouteImport
      parentRoute: typeof AuthenticatedCadreRoute
    }
    '/_authenticated/dashboard/users': {
      id: '/_authenticated/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof AuthenticatedDashboardUsersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/reports': {
      id: '/_authenticated/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof AuthenticatedDashboardReportsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/help': {
      id: '/_authenticated/dashboard/help'
      path: '/help'
      fullPath: '/dashboard/help'
      preLoaderRoute: typeof AuthenticatedDashboardHelpRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/evidence': {
      id: '/_authenticated/dashboard/evidence'
      path: '/evidence'
      fullPath: '/dashboard/evidence'
      preLoaderRoute: typeof AuthenticatedDashboardEvidenceRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/attendance': {
      id: '/_authenticated/dashboard/attendance'
      path: '/attendance'
      fullPath: '/dashboard/attendance'
      preLoaderRoute: typeof AuthenticatedDashboardAttendanceRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/approvals': {
      id: '/_authenticated/dashboard/approvals'
      path: '/approvals'
      fullPath: '/dashboard/approvals'
      preLoaderRoute: typeof AuthenticatedDashboardApprovalsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/activities': {
      id: '/_authenticated/dashboard/activities'
      path: '/activities'
      fullPath: '/dashboard/activities'
      preLoaderRoute: typeof AuthenticatedDashboardActivitiesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/cadre/submit': {
      id: '/_authenticated/cadre/submit'
      path: '/submit'
      fullPath: '/cadre/submit'
      preLoaderRoute: typeof AuthenticatedCadreSubmitRouteImport
      parentRoute: typeof AuthenticatedCadreRoute
    }
    '/_authenticated/cadre/profile': {
      id: '/_authenticated/cadre/profile'
      path: '/profile'
      fullPath: '/cadre/profile'
      preLoaderRoute: typeof AuthenticatedCadreProfileRouteImport
      parentRoute: typeof AuthenticatedCadreRoute
    }
    '/_authenticated/cadre/notifications': {
      id: '/_authenticated/cadre/notifications'
      path: '/notifications'
      fullPath: '/cadre/notifications'
      preLoaderRoute: typeof AuthenticatedCadreNotificationsRouteImport
      parentRoute: typeof AuthenticatedCadreRoute
    }
    '/_authenticated/cadre/history': {
      id: '/_authenticated/cadre/history'
      path: '/history'
      fullPath: '/cadre/history'
      preLoaderRoute: typeof AuthenticatedCadreHistoryRouteImport
      parentRoute: typeof AuthenticatedCadreRoute
    }
    '/_authenticated/cadre/help': {
      id: '/_authenticated/cadre/help'
      path: '/help'
      fullPath: '/cadre/help'
      preLoaderRoute: typeof AuthenticatedCadreHelpRouteImport
      parentRoute: typeof AuthenticatedCadreRoute
    }
  }
}

interface AuthenticatedCadreRouteChildren {
  AuthenticatedCadreHelpRoute: typeof AuthenticatedCadreHelpRoute
  AuthenticatedCadreHistoryRoute: typeof AuthenticatedCadreHistoryRoute
  AuthenticatedCadreNotificationsRoute: typeof AuthenticatedCadreNotificationsRoute
  AuthenticatedCadreProfileRoute: typeof AuthenticatedCadreProfileRoute
  AuthenticatedCadreSubmitRoute: typeof AuthenticatedCadreSubmitRoute
  AuthenticatedCadreIndexRoute: typeof AuthenticatedCadreIndexRoute
}

const AuthenticatedCadreRouteChildren: AuthenticatedCadreRouteChildren = {
  AuthenticatedCadreHelpRoute: AuthenticatedCadreHelpRoute,
  AuthenticatedCadreHistoryRoute: AuthenticatedCadreHistoryRoute,
  AuthenticatedCadreNotificationsRoute: AuthenticatedCadreNotificationsRoute,
  AuthenticatedCadreProfileRoute: AuthenticatedCadreProfileRoute,
  AuthenticatedCadreSubmitRoute: AuthenticatedCadreSubmitRoute,
  AuthenticatedCadreIndexRoute: AuthenticatedCadreIndexRoute,
}

const AuthenticatedCadreRouteWithChildren =
  AuthenticatedCadreRoute._addFileChildren(AuthenticatedCadreRouteChildren)

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardActivitiesRoute: typeof AuthenticatedDashboardActivitiesRoute
  AuthenticatedDashboardApprovalsRoute: typeof AuthenticatedDashboardApprovalsRoute
  AuthenticatedDashboardAttendanceRoute: typeof AuthenticatedDashboardAttendanceRoute
  AuthenticatedDashboardEvidenceRoute: typeof AuthenticatedDashboardEvidenceRoute
  AuthenticatedDashboardHelpRoute: typeof AuthenticatedDashboardHelpRoute
  AuthenticatedDashboardReportsRoute: typeof AuthenticatedDashboardReportsRoute
  AuthenticatedDashboardUsersRoute: typeof AuthenticatedDashboardUsersRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardActivitiesRoute:
      AuthenticatedDashboardActivitiesRoute,
    AuthenticatedDashboardApprovalsRoute: AuthenticatedDashboardApprovalsRoute,
    AuthenticatedDashboardAttendanceRoute:
      AuthenticatedDashboardAttendanceRoute,
    AuthenticatedDashboardEvidenceRoute: AuthenticatedDashboardEvidenceRoute,
    AuthenticatedDashboardHelpRoute: AuthenticatedDashboardHelpRoute,
    AuthenticatedDashboardReportsRoute: AuthenticatedDashboardReportsRoute,
    AuthenticatedDashboardUsersRoute: AuthenticatedDashboardUsersRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCadreRoute: typeof AuthenticatedCadreRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCadreRoute: AuthenticatedCadreRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
