// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";

function getCachedAccessToken() {
  if (typeof window === "undefined") return null;

  for (let i = 0; i < window.localStorage.length; i++) {
    const key = window.localStorage.key(i);
    if (!key?.startsWith("sb-") || !key.endsWith("-auth-token")) continue;

    try {
      const raw = window.localStorage.getItem(key);
      if (!raw) continue;
      const parsed = JSON.parse(raw);
      const session = parsed?.currentSession ?? parsed;
      const accessToken = session?.access_token;
      const expiresAt = Number(session?.expires_at ?? 0);

      if (accessToken && expiresAt * 1000 > Date.now() + 30_000) {
        return accessToken as string;
      }
    } catch {
      window.localStorage.removeItem(key);
    }
  }

  return null;
}

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    const token = getCachedAccessToken();
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    });
  },
);
